export {default as SignUpPage} from './SignUpPage'
export { default as HomePage} from './HomePage'
export { default as ProfilePage} from './ProfilePage'
export { default as LogInPage} from './LogInPage'
export {default as ReligiousPage} from './ReligiousPage'
export {default as SendSolanaPage } from './SendSolanaPage'